/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Community;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommunityRecord extends UpdatableRecordImpl<CommunityRecord> implements Record6<UInteger, String, Integer, Integer, Integer, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.community.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.community.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.community.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.community.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.community.capacity</code>.
     */
    public void setCapacity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.community.capacity</code>.
     */
    public Integer getCapacity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>housinggame.community.protection_rain_flood</code>.
     */
    public void setProtectionRainFlood(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.community.protection_rain_flood</code>.
     */
    public Integer getProtectionRainFlood() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>housinggame.community.protection_river_flood</code>.
     */
    public void setProtectionRiverFlood(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.community.protection_river_flood</code>.
     */
    public Integer getProtectionRiverFlood() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>housinggame.community.gameversion_id</code>.
     */
    public void setGameversionId(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.community.gameversion_id</code>.
     */
    public UInteger getGameversionId() {
        return (UInteger) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, String, Integer, Integer, Integer, UInteger> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UInteger, String, Integer, Integer, Integer, UInteger> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Community.COMMUNITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Community.COMMUNITY.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Community.COMMUNITY.CAPACITY;
    }

    @Override
    public Field<Integer> field4() {
        return Community.COMMUNITY.PROTECTION_RAIN_FLOOD;
    }

    @Override
    public Field<Integer> field5() {
        return Community.COMMUNITY.PROTECTION_RIVER_FLOOD;
    }

    @Override
    public Field<UInteger> field6() {
        return Community.COMMUNITY.GAMEVERSION_ID;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCapacity();
    }

    @Override
    public Integer component4() {
        return getProtectionRainFlood();
    }

    @Override
    public Integer component5() {
        return getProtectionRiverFlood();
    }

    @Override
    public UInteger component6() {
        return getGameversionId();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCapacity();
    }

    @Override
    public Integer value4() {
        return getProtectionRainFlood();
    }

    @Override
    public Integer value5() {
        return getProtectionRiverFlood();
    }

    @Override
    public UInteger value6() {
        return getGameversionId();
    }

    @Override
    public CommunityRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public CommunityRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CommunityRecord value3(Integer value) {
        setCapacity(value);
        return this;
    }

    @Override
    public CommunityRecord value4(Integer value) {
        setProtectionRainFlood(value);
        return this;
    }

    @Override
    public CommunityRecord value5(Integer value) {
        setProtectionRiverFlood(value);
        return this;
    }

    @Override
    public CommunityRecord value6(UInteger value) {
        setGameversionId(value);
        return this;
    }

    @Override
    public CommunityRecord values(UInteger value1, String value2, Integer value3, Integer value4, Integer value5, UInteger value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommunityRecord
     */
    public CommunityRecord() {
        super(Community.COMMUNITY);
    }

    /**
     * Create a detached, initialised CommunityRecord
     */
    public CommunityRecord(UInteger id, String name, Integer capacity, Integer protectionRainFlood, Integer protectionRiverFlood, UInteger gameversionId) {
        super(Community.COMMUNITY);

        setId(id);
        setName(name);
        setCapacity(capacity);
        setProtectionRainFlood(protectionRainFlood);
        setProtectionRiverFlood(protectionRiverFlood);
        setGameversionId(gameversionId);
        resetChangedOnNotNull();
    }
}
