/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import java.time.LocalDateTime;

import nl.tudelft.simulation.housinggame.data.tables.Groupround;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouproundRecord extends UpdatableRecordImpl<GrouproundRecord> implements Record7<Integer, Integer, Integer, LocalDateTime, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.groupround.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.groupround.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.groupround.pluvial_flood_intensity</code>.
     */
    public void setPluvialFloodIntensity(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.groupround.pluvial_flood_intensity</code>.
     */
    public Integer getPluvialFloodIntensity() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>housinggame.groupround.fluvial_flood_intensity</code>.
     */
    public void setFluvialFloodIntensity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.groupround.fluvial_flood_intensity</code>.
     */
    public Integer getFluvialFloodIntensity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>housinggame.groupround.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.groupround.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>housinggame.groupround.round_state</code>.
     */
    public void setRoundState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.groupround.round_state</code>.
     */
    public String getRoundState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>housinggame.groupround.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.groupround.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>housinggame.groupround.round_id</code>.
     */
    public void setRoundId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.groupround.round_id</code>.
     */
    public Integer getRoundId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, String, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Groupround.GROUPROUND.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Groupround.GROUPROUND.PLUVIAL_FLOOD_INTENSITY;
    }

    @Override
    public Field<Integer> field3() {
        return Groupround.GROUPROUND.FLUVIAL_FLOOD_INTENSITY;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Groupround.GROUPROUND.START_TIME;
    }

    @Override
    public Field<String> field5() {
        return Groupround.GROUPROUND.ROUND_STATE;
    }

    @Override
    public Field<Integer> field6() {
        return Groupround.GROUPROUND.GROUP_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Groupround.GROUPROUND.ROUND_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPluvialFloodIntensity();
    }

    @Override
    public Integer component3() {
        return getFluvialFloodIntensity();
    }

    @Override
    public LocalDateTime component4() {
        return getStartTime();
    }

    @Override
    public String component5() {
        return getRoundState();
    }

    @Override
    public Integer component6() {
        return getGroupId();
    }

    @Override
    public Integer component7() {
        return getRoundId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPluvialFloodIntensity();
    }

    @Override
    public Integer value3() {
        return getFluvialFloodIntensity();
    }

    @Override
    public LocalDateTime value4() {
        return getStartTime();
    }

    @Override
    public String value5() {
        return getRoundState();
    }

    @Override
    public Integer value6() {
        return getGroupId();
    }

    @Override
    public Integer value7() {
        return getRoundId();
    }

    @Override
    public GrouproundRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GrouproundRecord value2(Integer value) {
        setPluvialFloodIntensity(value);
        return this;
    }

    @Override
    public GrouproundRecord value3(Integer value) {
        setFluvialFloodIntensity(value);
        return this;
    }

    @Override
    public GrouproundRecord value4(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public GrouproundRecord value5(String value) {
        setRoundState(value);
        return this;
    }

    @Override
    public GrouproundRecord value6(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public GrouproundRecord value7(Integer value) {
        setRoundId(value);
        return this;
    }

    @Override
    public GrouproundRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, String value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrouproundRecord
     */
    public GrouproundRecord() {
        super(Groupround.GROUPROUND);
    }

    /**
     * Create a detached, initialised GrouproundRecord
     */
    public GrouproundRecord(Integer id, Integer pluvialFloodIntensity, Integer fluvialFloodIntensity, LocalDateTime startTime, String roundState, Integer groupId, Integer roundId) {
        super(Groupround.GROUPROUND);

        setId(id);
        setPluvialFloodIntensity(pluvialFloodIntensity);
        setFluvialFloodIntensity(fluvialFloodIntensity);
        setStartTime(startTime);
        setRoundState(roundState);
        setGroupId(groupId);
        setRoundId(roundId);
        resetChangedOnNotNull();
    }
}
