/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Housegroup;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HousegroupRecord extends UpdatableRecordImpl<HousegroupRecord> implements Record21<Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.housegroup.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.housegroup.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.housegroup.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>housinggame.housegroup.rating</code>.
     */
    public void setRating(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>housinggame.housegroup.original_price</code>.
     */
    public void setOriginalPrice(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.original_price</code>.
     */
    public Integer getOriginalPrice() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>housinggame.housegroup.damage_reduction</code>.
     */
    public void setDamageReduction(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.damage_reduction</code>.
     */
    public Integer getDamageReduction() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>housinggame.housegroup.market_value</code>.
     */
    public void setMarketValue(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.market_value</code>.
     */
    public Integer getMarketValue() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>housinggame.housegroup.last_sold_price</code>.
     */
    public void setLastSoldPrice(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.last_sold_price</code>.
     */
    public Integer getLastSoldPrice() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>housinggame.housegroup.house_satisfaction</code>.
     */
    public void setHouseSatisfaction(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.house_satisfaction</code>.
     */
    public Integer getHouseSatisfaction() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>housinggame.housegroup.status</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>housinggame.housegroup.fluvial_base_protection</code>.
     */
    public void setFluvialBaseProtection(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.fluvial_base_protection</code>.
     */
    public Integer getFluvialBaseProtection() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>housinggame.housegroup.pluvial_base_protection</code>.
     */
    public void setPluvialBaseProtection(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.pluvial_base_protection</code>.
     */
    public Integer getPluvialBaseProtection() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>housinggame.housegroup.fluvial_house_protection</code>.
     */
    public void setFluvialHouseProtection(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.fluvial_house_protection</code>.
     */
    public Integer getFluvialHouseProtection() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>housinggame.housegroup.pluvial_house_protection</code>.
     */
    public void setPluvialHouseProtection(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.pluvial_house_protection</code>.
     */
    public Integer getPluvialHouseProtection() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>housinggame.housegroup.last_round_comm_fluvial</code>.
     */
    public void setLastRoundCommFluvial(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.last_round_comm_fluvial</code>.
     */
    public Integer getLastRoundCommFluvial() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>housinggame.housegroup.last_round_comm_pluvial</code>.
     */
    public void setLastRoundCommPluvial(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.last_round_comm_pluvial</code>.
     */
    public Integer getLastRoundCommPluvial() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>housinggame.housegroup.last_round_house_fluvial</code>.
     */
    public void setLastRoundHouseFluvial(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.last_round_house_fluvial</code>.
     */
    public Integer getLastRoundHouseFluvial() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>housinggame.housegroup.last_round_house_pluvial</code>.
     */
    public void setLastRoundHousePluvial(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.last_round_house_pluvial</code>.
     */
    public Integer getLastRoundHousePluvial() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>housinggame.housegroup.house_id</code>.
     */
    public void setHouseId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.house_id</code>.
     */
    public Integer getHouseId() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>housinggame.housegroup.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>housinggame.housegroup.owner_id</code>.
     */
    public void setOwnerId(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.owner_id</code>.
     */
    public Integer getOwnerId() {
        return (Integer) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Housegroup.HOUSEGROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return Housegroup.HOUSEGROUP.CODE;
    }

    @Override
    public Field<String> field3() {
        return Housegroup.HOUSEGROUP.ADDRESS;
    }

    @Override
    public Field<Integer> field4() {
        return Housegroup.HOUSEGROUP.RATING;
    }

    @Override
    public Field<Integer> field5() {
        return Housegroup.HOUSEGROUP.ORIGINAL_PRICE;
    }

    @Override
    public Field<Integer> field6() {
        return Housegroup.HOUSEGROUP.DAMAGE_REDUCTION;
    }

    @Override
    public Field<Integer> field7() {
        return Housegroup.HOUSEGROUP.MARKET_VALUE;
    }

    @Override
    public Field<Integer> field8() {
        return Housegroup.HOUSEGROUP.LAST_SOLD_PRICE;
    }

    @Override
    public Field<Integer> field9() {
        return Housegroup.HOUSEGROUP.HOUSE_SATISFACTION;
    }

    @Override
    public Field<String> field10() {
        return Housegroup.HOUSEGROUP.STATUS;
    }

    @Override
    public Field<Integer> field11() {
        return Housegroup.HOUSEGROUP.FLUVIAL_BASE_PROTECTION;
    }

    @Override
    public Field<Integer> field12() {
        return Housegroup.HOUSEGROUP.PLUVIAL_BASE_PROTECTION;
    }

    @Override
    public Field<Integer> field13() {
        return Housegroup.HOUSEGROUP.FLUVIAL_HOUSE_PROTECTION;
    }

    @Override
    public Field<Integer> field14() {
        return Housegroup.HOUSEGROUP.PLUVIAL_HOUSE_PROTECTION;
    }

    @Override
    public Field<Integer> field15() {
        return Housegroup.HOUSEGROUP.LAST_ROUND_COMM_FLUVIAL;
    }

    @Override
    public Field<Integer> field16() {
        return Housegroup.HOUSEGROUP.LAST_ROUND_COMM_PLUVIAL;
    }

    @Override
    public Field<Integer> field17() {
        return Housegroup.HOUSEGROUP.LAST_ROUND_HOUSE_FLUVIAL;
    }

    @Override
    public Field<Integer> field18() {
        return Housegroup.HOUSEGROUP.LAST_ROUND_HOUSE_PLUVIAL;
    }

    @Override
    public Field<Integer> field19() {
        return Housegroup.HOUSEGROUP.HOUSE_ID;
    }

    @Override
    public Field<Integer> field20() {
        return Housegroup.HOUSEGROUP.GROUP_ID;
    }

    @Override
    public Field<Integer> field21() {
        return Housegroup.HOUSEGROUP.OWNER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getAddress();
    }

    @Override
    public Integer component4() {
        return getRating();
    }

    @Override
    public Integer component5() {
        return getOriginalPrice();
    }

    @Override
    public Integer component6() {
        return getDamageReduction();
    }

    @Override
    public Integer component7() {
        return getMarketValue();
    }

    @Override
    public Integer component8() {
        return getLastSoldPrice();
    }

    @Override
    public Integer component9() {
        return getHouseSatisfaction();
    }

    @Override
    public String component10() {
        return getStatus();
    }

    @Override
    public Integer component11() {
        return getFluvialBaseProtection();
    }

    @Override
    public Integer component12() {
        return getPluvialBaseProtection();
    }

    @Override
    public Integer component13() {
        return getFluvialHouseProtection();
    }

    @Override
    public Integer component14() {
        return getPluvialHouseProtection();
    }

    @Override
    public Integer component15() {
        return getLastRoundCommFluvial();
    }

    @Override
    public Integer component16() {
        return getLastRoundCommPluvial();
    }

    @Override
    public Integer component17() {
        return getLastRoundHouseFluvial();
    }

    @Override
    public Integer component18() {
        return getLastRoundHousePluvial();
    }

    @Override
    public Integer component19() {
        return getHouseId();
    }

    @Override
    public Integer component20() {
        return getGroupId();
    }

    @Override
    public Integer component21() {
        return getOwnerId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getAddress();
    }

    @Override
    public Integer value4() {
        return getRating();
    }

    @Override
    public Integer value5() {
        return getOriginalPrice();
    }

    @Override
    public Integer value6() {
        return getDamageReduction();
    }

    @Override
    public Integer value7() {
        return getMarketValue();
    }

    @Override
    public Integer value8() {
        return getLastSoldPrice();
    }

    @Override
    public Integer value9() {
        return getHouseSatisfaction();
    }

    @Override
    public String value10() {
        return getStatus();
    }

    @Override
    public Integer value11() {
        return getFluvialBaseProtection();
    }

    @Override
    public Integer value12() {
        return getPluvialBaseProtection();
    }

    @Override
    public Integer value13() {
        return getFluvialHouseProtection();
    }

    @Override
    public Integer value14() {
        return getPluvialHouseProtection();
    }

    @Override
    public Integer value15() {
        return getLastRoundCommFluvial();
    }

    @Override
    public Integer value16() {
        return getLastRoundCommPluvial();
    }

    @Override
    public Integer value17() {
        return getLastRoundHouseFluvial();
    }

    @Override
    public Integer value18() {
        return getLastRoundHousePluvial();
    }

    @Override
    public Integer value19() {
        return getHouseId();
    }

    @Override
    public Integer value20() {
        return getGroupId();
    }

    @Override
    public Integer value21() {
        return getOwnerId();
    }

    @Override
    public HousegroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HousegroupRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public HousegroupRecord value3(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public HousegroupRecord value4(Integer value) {
        setRating(value);
        return this;
    }

    @Override
    public HousegroupRecord value5(Integer value) {
        setOriginalPrice(value);
        return this;
    }

    @Override
    public HousegroupRecord value6(Integer value) {
        setDamageReduction(value);
        return this;
    }

    @Override
    public HousegroupRecord value7(Integer value) {
        setMarketValue(value);
        return this;
    }

    @Override
    public HousegroupRecord value8(Integer value) {
        setLastSoldPrice(value);
        return this;
    }

    @Override
    public HousegroupRecord value9(Integer value) {
        setHouseSatisfaction(value);
        return this;
    }

    @Override
    public HousegroupRecord value10(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public HousegroupRecord value11(Integer value) {
        setFluvialBaseProtection(value);
        return this;
    }

    @Override
    public HousegroupRecord value12(Integer value) {
        setPluvialBaseProtection(value);
        return this;
    }

    @Override
    public HousegroupRecord value13(Integer value) {
        setFluvialHouseProtection(value);
        return this;
    }

    @Override
    public HousegroupRecord value14(Integer value) {
        setPluvialHouseProtection(value);
        return this;
    }

    @Override
    public HousegroupRecord value15(Integer value) {
        setLastRoundCommFluvial(value);
        return this;
    }

    @Override
    public HousegroupRecord value16(Integer value) {
        setLastRoundCommPluvial(value);
        return this;
    }

    @Override
    public HousegroupRecord value17(Integer value) {
        setLastRoundHouseFluvial(value);
        return this;
    }

    @Override
    public HousegroupRecord value18(Integer value) {
        setLastRoundHousePluvial(value);
        return this;
    }

    @Override
    public HousegroupRecord value19(Integer value) {
        setHouseId(value);
        return this;
    }

    @Override
    public HousegroupRecord value20(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public HousegroupRecord value21(Integer value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public HousegroupRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, Integer value16, Integer value17, Integer value18, Integer value19, Integer value20, Integer value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HousegroupRecord
     */
    public HousegroupRecord() {
        super(Housegroup.HOUSEGROUP);
    }

    /**
     * Create a detached, initialised HousegroupRecord
     */
    public HousegroupRecord(Integer id, String code, String address, Integer rating, Integer originalPrice, Integer damageReduction, Integer marketValue, Integer lastSoldPrice, Integer houseSatisfaction, String status, Integer fluvialBaseProtection, Integer pluvialBaseProtection, Integer fluvialHouseProtection, Integer pluvialHouseProtection, Integer lastRoundCommFluvial, Integer lastRoundCommPluvial, Integer lastRoundHouseFluvial, Integer lastRoundHousePluvial, Integer houseId, Integer groupId, Integer ownerId) {
        super(Housegroup.HOUSEGROUP);

        setId(id);
        setCode(code);
        setAddress(address);
        setRating(rating);
        setOriginalPrice(originalPrice);
        setDamageReduction(damageReduction);
        setMarketValue(marketValue);
        setLastSoldPrice(lastSoldPrice);
        setHouseSatisfaction(houseSatisfaction);
        setStatus(status);
        setFluvialBaseProtection(fluvialBaseProtection);
        setPluvialBaseProtection(pluvialBaseProtection);
        setFluvialHouseProtection(fluvialHouseProtection);
        setPluvialHouseProtection(pluvialHouseProtection);
        setLastRoundCommFluvial(lastRoundCommFluvial);
        setLastRoundCommPluvial(lastRoundCommPluvial);
        setLastRoundHouseFluvial(lastRoundHouseFluvial);
        setLastRoundHousePluvial(lastRoundHousePluvial);
        setHouseId(houseId);
        setGroupId(groupId);
        setOwnerId(ownerId);
        resetChangedOnNotNull();
    }
}
