/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.House;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HouseRecord extends UpdatableRecordImpl<HouseRecord> implements Record9<UInteger, UInteger, String, UInteger, String, UInteger, Integer, Integer, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.house.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.house.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.house.price</code>.
     */
    public void setPrice(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.house.price</code>.
     */
    public UInteger getPrice() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>housinggame.house.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.house.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>housinggame.house.available_round</code>.
     */
    public void setAvailableRound(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.house.available_round</code>.
     */
    public UInteger getAvailableRound() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>housinggame.house.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.house.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>housinggame.house.rating</code>.
     */
    public void setRating(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.house.rating</code>.
     */
    public UInteger getRating() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>housinggame.house.initial_pluvial_protection</code>.
     */
    public void setInitialPluvialProtection(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.house.initial_pluvial_protection</code>.
     */
    public Integer getInitialPluvialProtection() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>housinggame.house.initial_fluvial_protection</code>.
     */
    public void setInitialFluvialProtection(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>housinggame.house.initial_fluvial_protection</code>.
     */
    public Integer getInitialFluvialProtection() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>housinggame.house.community_id</code>.
     */
    public void setCommunityId(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>housinggame.house.community_id</code>.
     */
    public UInteger getCommunityId() {
        return (UInteger) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UInteger, UInteger, String, UInteger, String, UInteger, Integer, Integer, UInteger> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UInteger, UInteger, String, UInteger, String, UInteger, Integer, Integer, UInteger> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return House.HOUSE.ID;
    }

    @Override
    public Field<UInteger> field2() {
        return House.HOUSE.PRICE;
    }

    @Override
    public Field<String> field3() {
        return House.HOUSE.ADDRESS;
    }

    @Override
    public Field<UInteger> field4() {
        return House.HOUSE.AVAILABLE_ROUND;
    }

    @Override
    public Field<String> field5() {
        return House.HOUSE.DESCRIPTION;
    }

    @Override
    public Field<UInteger> field6() {
        return House.HOUSE.RATING;
    }

    @Override
    public Field<Integer> field7() {
        return House.HOUSE.INITIAL_PLUVIAL_PROTECTION;
    }

    @Override
    public Field<Integer> field8() {
        return House.HOUSE.INITIAL_FLUVIAL_PROTECTION;
    }

    @Override
    public Field<UInteger> field9() {
        return House.HOUSE.COMMUNITY_ID;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public UInteger component2() {
        return getPrice();
    }

    @Override
    public String component3() {
        return getAddress();
    }

    @Override
    public UInteger component4() {
        return getAvailableRound();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public UInteger component6() {
        return getRating();
    }

    @Override
    public Integer component7() {
        return getInitialPluvialProtection();
    }

    @Override
    public Integer component8() {
        return getInitialFluvialProtection();
    }

    @Override
    public UInteger component9() {
        return getCommunityId();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public UInteger value2() {
        return getPrice();
    }

    @Override
    public String value3() {
        return getAddress();
    }

    @Override
    public UInteger value4() {
        return getAvailableRound();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public UInteger value6() {
        return getRating();
    }

    @Override
    public Integer value7() {
        return getInitialPluvialProtection();
    }

    @Override
    public Integer value8() {
        return getInitialFluvialProtection();
    }

    @Override
    public UInteger value9() {
        return getCommunityId();
    }

    @Override
    public HouseRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public HouseRecord value2(UInteger value) {
        setPrice(value);
        return this;
    }

    @Override
    public HouseRecord value3(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public HouseRecord value4(UInteger value) {
        setAvailableRound(value);
        return this;
    }

    @Override
    public HouseRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public HouseRecord value6(UInteger value) {
        setRating(value);
        return this;
    }

    @Override
    public HouseRecord value7(Integer value) {
        setInitialPluvialProtection(value);
        return this;
    }

    @Override
    public HouseRecord value8(Integer value) {
        setInitialFluvialProtection(value);
        return this;
    }

    @Override
    public HouseRecord value9(UInteger value) {
        setCommunityId(value);
        return this;
    }

    @Override
    public HouseRecord values(UInteger value1, UInteger value2, String value3, UInteger value4, String value5, UInteger value6, Integer value7, Integer value8, UInteger value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HouseRecord
     */
    public HouseRecord() {
        super(House.HOUSE);
    }

    /**
     * Create a detached, initialised HouseRecord
     */
    public HouseRecord(UInteger id, UInteger price, String address, UInteger availableRound, String description, UInteger rating, Integer initialPluvialProtection, Integer initialFluvialProtection, UInteger communityId) {
        super(House.HOUSE);

        setId(id);
        setPrice(price);
        setAddress(address);
        setAvailableRound(availableRound);
        setDescription(description);
        setRating(rating);
        setInitialPluvialProtection(initialPluvialProtection);
        setInitialFluvialProtection(initialFluvialProtection);
        setCommunityId(communityId);
        resetChangedOnNotNull();
    }
}
