/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Houseround;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HouseroundRecord extends UpdatableRecordImpl<HouseroundRecord> implements Record9<Integer, String, Integer, String, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.houseround.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.houseround.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.houseround.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.houseround.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.houseround.bid_price</code>.
     */
    public void setBidPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.houseround.bid_price</code>.
     */
    public Integer getBidPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>housinggame.houseround.bid_explanation</code>.
     */
    public void setBidExplanation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.houseround.bid_explanation</code>.
     */
    public String getBidExplanation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>housinggame.houseround.undamaged_price</code>.
     */
    public void setUndamagedPrice(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.houseround.undamaged_price</code>.
     */
    public Integer getUndamagedPrice() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>housinggame.houseround.damage_reduction</code>.
     */
    public void setDamageReduction(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.houseround.damage_reduction</code>.
     */
    public Integer getDamageReduction() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>housinggame.houseround.house_satisfaction</code>.
     */
    public void setHouseSatisfaction(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.houseround.house_satisfaction</code>.
     */
    public Integer getHouseSatisfaction() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>housinggame.houseround.groupround_id</code>.
     */
    public void setGrouproundId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>housinggame.houseround.groupround_id</code>.
     */
    public Integer getGrouproundId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>housinggame.houseround.house_id</code>.
     */
    public void setHouseId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>housinggame.houseround.house_id</code>.
     */
    public Integer getHouseId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, Integer, String, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, Integer, String, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Houseround.HOUSEROUND.ID;
    }

    @Override
    public Field<String> field2() {
        return Houseround.HOUSEROUND.CODE;
    }

    @Override
    public Field<Integer> field3() {
        return Houseround.HOUSEROUND.BID_PRICE;
    }

    @Override
    public Field<String> field4() {
        return Houseround.HOUSEROUND.BID_EXPLANATION;
    }

    @Override
    public Field<Integer> field5() {
        return Houseround.HOUSEROUND.UNDAMAGED_PRICE;
    }

    @Override
    public Field<Integer> field6() {
        return Houseround.HOUSEROUND.DAMAGE_REDUCTION;
    }

    @Override
    public Field<Integer> field7() {
        return Houseround.HOUSEROUND.HOUSE_SATISFACTION;
    }

    @Override
    public Field<Integer> field8() {
        return Houseround.HOUSEROUND.GROUPROUND_ID;
    }

    @Override
    public Field<Integer> field9() {
        return Houseround.HOUSEROUND.HOUSE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public Integer component3() {
        return getBidPrice();
    }

    @Override
    public String component4() {
        return getBidExplanation();
    }

    @Override
    public Integer component5() {
        return getUndamagedPrice();
    }

    @Override
    public Integer component6() {
        return getDamageReduction();
    }

    @Override
    public Integer component7() {
        return getHouseSatisfaction();
    }

    @Override
    public Integer component8() {
        return getGrouproundId();
    }

    @Override
    public Integer component9() {
        return getHouseId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public Integer value3() {
        return getBidPrice();
    }

    @Override
    public String value4() {
        return getBidExplanation();
    }

    @Override
    public Integer value5() {
        return getUndamagedPrice();
    }

    @Override
    public Integer value6() {
        return getDamageReduction();
    }

    @Override
    public Integer value7() {
        return getHouseSatisfaction();
    }

    @Override
    public Integer value8() {
        return getGrouproundId();
    }

    @Override
    public Integer value9() {
        return getHouseId();
    }

    @Override
    public HouseroundRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HouseroundRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public HouseroundRecord value3(Integer value) {
        setBidPrice(value);
        return this;
    }

    @Override
    public HouseroundRecord value4(String value) {
        setBidExplanation(value);
        return this;
    }

    @Override
    public HouseroundRecord value5(Integer value) {
        setUndamagedPrice(value);
        return this;
    }

    @Override
    public HouseroundRecord value6(Integer value) {
        setDamageReduction(value);
        return this;
    }

    @Override
    public HouseroundRecord value7(Integer value) {
        setHouseSatisfaction(value);
        return this;
    }

    @Override
    public HouseroundRecord value8(Integer value) {
        setGrouproundId(value);
        return this;
    }

    @Override
    public HouseroundRecord value9(Integer value) {
        setHouseId(value);
        return this;
    }

    @Override
    public HouseroundRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HouseroundRecord
     */
    public HouseroundRecord() {
        super(Houseround.HOUSEROUND);
    }

    /**
     * Create a detached, initialised HouseroundRecord
     */
    public HouseroundRecord(Integer id, String code, Integer bidPrice, String bidExplanation, Integer undamagedPrice, Integer damageReduction, Integer houseSatisfaction, Integer grouproundId, Integer houseId) {
        super(Houseround.HOUSEROUND);

        setId(id);
        setCode(code);
        setBidPrice(bidPrice);
        setBidExplanation(bidExplanation);
        setUndamagedPrice(undamagedPrice);
        setDamageReduction(damageReduction);
        setHouseSatisfaction(houseSatisfaction);
        setGrouproundId(grouproundId);
        setHouseId(houseId);
        resetChangedOnNotNull();
    }
}
