/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Housegroup;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HousegroupRecord extends UpdatableRecordImpl<HousegroupRecord> implements Record10<Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.housegroup.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.housegroup.original_price</code>.
     */
    public void setOriginalPrice(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.original_price</code>.
     */
    public Integer getOriginalPrice() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>housinggame.housegroup.damage_reduction</code>.
     */
    public void setDamageReduction(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.damage_reduction</code>.
     */
    public Integer getDamageReduction() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>housinggame.housegroup.market_value</code>.
     */
    public void setMarketValue(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.market_value</code>.
     */
    public Integer getMarketValue() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>housinggame.housegroup.last_sold_price</code>.
     */
    public void setLastSoldPrice(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.last_sold_price</code>.
     */
    public Integer getLastSoldPrice() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>housinggame.housegroup.house_satisfaction</code>.
     */
    public void setHouseSatisfaction(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.house_satisfaction</code>.
     */
    public Integer getHouseSatisfaction() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>housinggame.housegroup.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>housinggame.housegroup.house_id</code>.
     */
    public void setHouseId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.house_id</code>.
     */
    public Integer getHouseId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>housinggame.housegroup.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>housinggame.housegroup.owner_id</code>.
     */
    public void setOwnerId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>housinggame.housegroup.owner_id</code>.
     */
    public Integer getOwnerId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Housegroup.HOUSEGROUP.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Housegroup.HOUSEGROUP.ORIGINAL_PRICE;
    }

    @Override
    public Field<Integer> field3() {
        return Housegroup.HOUSEGROUP.DAMAGE_REDUCTION;
    }

    @Override
    public Field<Integer> field4() {
        return Housegroup.HOUSEGROUP.MARKET_VALUE;
    }

    @Override
    public Field<Integer> field5() {
        return Housegroup.HOUSEGROUP.LAST_SOLD_PRICE;
    }

    @Override
    public Field<Integer> field6() {
        return Housegroup.HOUSEGROUP.HOUSE_SATISFACTION;
    }

    @Override
    public Field<String> field7() {
        return Housegroup.HOUSEGROUP.STATUS;
    }

    @Override
    public Field<Integer> field8() {
        return Housegroup.HOUSEGROUP.HOUSE_ID;
    }

    @Override
    public Field<Integer> field9() {
        return Housegroup.HOUSEGROUP.GROUP_ID;
    }

    @Override
    public Field<Integer> field10() {
        return Housegroup.HOUSEGROUP.OWNER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOriginalPrice();
    }

    @Override
    public Integer component3() {
        return getDamageReduction();
    }

    @Override
    public Integer component4() {
        return getMarketValue();
    }

    @Override
    public Integer component5() {
        return getLastSoldPrice();
    }

    @Override
    public Integer component6() {
        return getHouseSatisfaction();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Integer component8() {
        return getHouseId();
    }

    @Override
    public Integer component9() {
        return getGroupId();
    }

    @Override
    public Integer component10() {
        return getOwnerId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOriginalPrice();
    }

    @Override
    public Integer value3() {
        return getDamageReduction();
    }

    @Override
    public Integer value4() {
        return getMarketValue();
    }

    @Override
    public Integer value5() {
        return getLastSoldPrice();
    }

    @Override
    public Integer value6() {
        return getHouseSatisfaction();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public Integer value8() {
        return getHouseId();
    }

    @Override
    public Integer value9() {
        return getGroupId();
    }

    @Override
    public Integer value10() {
        return getOwnerId();
    }

    @Override
    public HousegroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HousegroupRecord value2(Integer value) {
        setOriginalPrice(value);
        return this;
    }

    @Override
    public HousegroupRecord value3(Integer value) {
        setDamageReduction(value);
        return this;
    }

    @Override
    public HousegroupRecord value4(Integer value) {
        setMarketValue(value);
        return this;
    }

    @Override
    public HousegroupRecord value5(Integer value) {
        setLastSoldPrice(value);
        return this;
    }

    @Override
    public HousegroupRecord value6(Integer value) {
        setHouseSatisfaction(value);
        return this;
    }

    @Override
    public HousegroupRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public HousegroupRecord value8(Integer value) {
        setHouseId(value);
        return this;
    }

    @Override
    public HousegroupRecord value9(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public HousegroupRecord value10(Integer value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public HousegroupRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, String value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HousegroupRecord
     */
    public HousegroupRecord() {
        super(Housegroup.HOUSEGROUP);
    }

    /**
     * Create a detached, initialised HousegroupRecord
     */
    public HousegroupRecord(Integer id, Integer originalPrice, Integer damageReduction, Integer marketValue, Integer lastSoldPrice, Integer houseSatisfaction, String status, Integer houseId, Integer groupId, Integer ownerId) {
        super(Housegroup.HOUSEGROUP);

        setId(id);
        setOriginalPrice(originalPrice);
        setDamageReduction(damageReduction);
        setMarketValue(marketValue);
        setLastSoldPrice(lastSoldPrice);
        setHouseSatisfaction(houseSatisfaction);
        setStatus(status);
        setHouseId(houseId);
        setGroupId(groupId);
        setOwnerId(ownerId);
        resetChangedOnNotNull();
    }
}
