/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Label;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabelRecord extends UpdatableRecordImpl<LabelRecord> implements Record7<Integer, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.label.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.label.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.label.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.label.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.label.value1</code>.
     */
    public void setValue1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.label.value1</code>.
     */
    public String getValue1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>housinggame.label.value2</code>.
     */
    public void setValue2(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.label.value2</code>.
     */
    public String getValue2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>housinggame.label.value3</code>.
     */
    public void setValue3(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.label.value3</code>.
     */
    public String getValue3() {
        return (String) get(4);
    }

    /**
     * Setter for <code>housinggame.label.value4</code>.
     */
    public void setValue4(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.label.value4</code>.
     */
    public String getValue4() {
        return (String) get(5);
    }

    /**
     * Setter for <code>housinggame.label.languagegroup_id</code>.
     */
    public void setLanguagegroupId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.label.languagegroup_id</code>.
     */
    public Integer getLanguagegroupId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Label.LABEL.ID;
    }

    @Override
    public Field<String> field2() {
        return Label.LABEL.KEY;
    }

    @Override
    public Field<String> field3() {
        return Label.LABEL.VALUE1;
    }

    @Override
    public Field<String> field4() {
        return Label.LABEL.VALUE2;
    }

    @Override
    public Field<String> field5() {
        return Label.LABEL.VALUE3;
    }

    @Override
    public Field<String> field6() {
        return Label.LABEL.VALUE4;
    }

    @Override
    public Field<Integer> field7() {
        return Label.LABEL.LANGUAGEGROUP_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue1();
    }

    @Override
    public String component4() {
        return getValue2();
    }

    @Override
    public String component5() {
        return getValue3();
    }

    @Override
    public String component6() {
        return getValue4();
    }

    @Override
    public Integer component7() {
        return getLanguagegroupId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue1();
    }

    @Override
    public String value4() {
        return getValue2();
    }

    @Override
    public String value5() {
        return getValue3();
    }

    @Override
    public String value6() {
        return getValue4();
    }

    @Override
    public Integer value7() {
        return getLanguagegroupId();
    }

    @Override
    public LabelRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LabelRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public LabelRecord value3(String value) {
        setValue1(value);
        return this;
    }

    @Override
    public LabelRecord value4(String value) {
        setValue2(value);
        return this;
    }

    @Override
    public LabelRecord value5(String value) {
        setValue3(value);
        return this;
    }

    @Override
    public LabelRecord value6(String value) {
        setValue4(value);
        return this;
    }

    @Override
    public LabelRecord value7(Integer value) {
        setLanguagegroupId(value);
        return this;
    }

    @Override
    public LabelRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabelRecord
     */
    public LabelRecord() {
        super(Label.LABEL);
    }

    /**
     * Create a detached, initialised LabelRecord
     */
    public LabelRecord(Integer id, String key, String value1, String value2, String value3, String value4, Integer languagegroupId) {
        super(Label.LABEL);

        setId(id);
        setKey(key);
        setValue1(value1);
        setValue2(value2);
        setValue3(value3);
        setValue4(value4);
        setLanguagegroupId(languagegroupId);
        resetChangedOnNotNull();
    }
}
