/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import nl.tudelft.simulation.housinggame.data.tables.Languagegroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguagegroupRecord extends UpdatableRecordImpl<LanguagegroupRecord> implements Record6<Integer, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.languagegroup.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.languagegroup.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.languagegroup.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.languagegroup.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.languagegroup.language_id1</code>.
     */
    public void setLanguageId1(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.languagegroup.language_id1</code>.
     */
    public Integer getLanguageId1() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>housinggame.languagegroup.language_id2</code>.
     */
    public void setLanguageId2(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.languagegroup.language_id2</code>.
     */
    public Integer getLanguageId2() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>housinggame.languagegroup.language_id3</code>.
     */
    public void setLanguageId3(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.languagegroup.language_id3</code>.
     */
    public Integer getLanguageId3() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>housinggame.languagegroup.language_id4</code>.
     */
    public void setLanguageId4(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.languagegroup.language_id4</code>.
     */
    public Integer getLanguageId4() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Languagegroup.LANGUAGEGROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return Languagegroup.LANGUAGEGROUP.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Languagegroup.LANGUAGEGROUP.LANGUAGE_ID1;
    }

    @Override
    public Field<Integer> field4() {
        return Languagegroup.LANGUAGEGROUP.LANGUAGE_ID2;
    }

    @Override
    public Field<Integer> field5() {
        return Languagegroup.LANGUAGEGROUP.LANGUAGE_ID3;
    }

    @Override
    public Field<Integer> field6() {
        return Languagegroup.LANGUAGEGROUP.LANGUAGE_ID4;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getLanguageId1();
    }

    @Override
    public Integer component4() {
        return getLanguageId2();
    }

    @Override
    public Integer component5() {
        return getLanguageId3();
    }

    @Override
    public Integer component6() {
        return getLanguageId4();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getLanguageId1();
    }

    @Override
    public Integer value4() {
        return getLanguageId2();
    }

    @Override
    public Integer value5() {
        return getLanguageId3();
    }

    @Override
    public Integer value6() {
        return getLanguageId4();
    }

    @Override
    public LanguagegroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LanguagegroupRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LanguagegroupRecord value3(Integer value) {
        setLanguageId1(value);
        return this;
    }

    @Override
    public LanguagegroupRecord value4(Integer value) {
        setLanguageId2(value);
        return this;
    }

    @Override
    public LanguagegroupRecord value5(Integer value) {
        setLanguageId3(value);
        return this;
    }

    @Override
    public LanguagegroupRecord value6(Integer value) {
        setLanguageId4(value);
        return this;
    }

    @Override
    public LanguagegroupRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguagegroupRecord
     */
    public LanguagegroupRecord() {
        super(Languagegroup.LANGUAGEGROUP);
    }

    /**
     * Create a detached, initialised LanguagegroupRecord
     */
    public LanguagegroupRecord(Integer id, String name, Integer languageId1, Integer languageId2, Integer languageId3, Integer languageId4) {
        super(Languagegroup.LANGUAGEGROUP);

        setId(id);
        setName(name);
        setLanguageId1(languageId1);
        setLanguageId2(languageId2);
        setLanguageId3(languageId3);
        setLanguageId4(languageId4);
        resetChangedOnNotNull();
    }
}
