/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Movingreason;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovingreasonRecord extends UpdatableRecordImpl<MovingreasonRecord> implements Record5<Integer, Integer, String, Byte, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.movingreason.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.movingreason.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.movingreason.sequence_number</code>.
     */
    public void setSequenceNumber(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.movingreason.sequence_number</code>.
     */
    public Integer getSequenceNumber() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>housinggame.movingreason.reason_text</code>.
     */
    public void setReasonText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.movingreason.reason_text</code>.
     */
    public String getReasonText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>housinggame.movingreason.is_other</code>.
     */
    public void setIsOther(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.movingreason.is_other</code>.
     */
    public Byte getIsOther() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>housinggame.movingreason.gameversion_id</code>.
     */
    public void setGameversionId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.movingreason.gameversion_id</code>.
     */
    public Integer getGameversionId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Byte, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Byte, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Movingreason.MOVINGREASON.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Movingreason.MOVINGREASON.SEQUENCE_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return Movingreason.MOVINGREASON.REASON_TEXT;
    }

    @Override
    public Field<Byte> field4() {
        return Movingreason.MOVINGREASON.IS_OTHER;
    }

    @Override
    public Field<Integer> field5() {
        return Movingreason.MOVINGREASON.GAMEVERSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSequenceNumber();
    }

    @Override
    public String component3() {
        return getReasonText();
    }

    @Override
    public Byte component4() {
        return getIsOther();
    }

    @Override
    public Integer component5() {
        return getGameversionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSequenceNumber();
    }

    @Override
    public String value3() {
        return getReasonText();
    }

    @Override
    public Byte value4() {
        return getIsOther();
    }

    @Override
    public Integer value5() {
        return getGameversionId();
    }

    @Override
    public MovingreasonRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MovingreasonRecord value2(Integer value) {
        setSequenceNumber(value);
        return this;
    }

    @Override
    public MovingreasonRecord value3(String value) {
        setReasonText(value);
        return this;
    }

    @Override
    public MovingreasonRecord value4(Byte value) {
        setIsOther(value);
        return this;
    }

    @Override
    public MovingreasonRecord value5(Integer value) {
        setGameversionId(value);
        return this;
    }

    @Override
    public MovingreasonRecord values(Integer value1, Integer value2, String value3, Byte value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovingreasonRecord
     */
    public MovingreasonRecord() {
        super(Movingreason.MOVINGREASON);
    }

    /**
     * Create a detached, initialised MovingreasonRecord
     */
    public MovingreasonRecord(Integer id, Integer sequenceNumber, String reasonText, Byte isOther, Integer gameversionId) {
        super(Movingreason.MOVINGREASON);

        setId(id);
        setSequenceNumber(sequenceNumber);
        setReasonText(reasonText);
        setIsOther(isOther);
        setGameversionId(gameversionId);
        resetChangedOnNotNull();
    }
}
