/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Player;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> implements Record5<UInteger, String, UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.player.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.player.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.player.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.player.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.player.user_id</code>.
     */
    public void setUserId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.player.user_id</code>.
     */
    public UInteger getUserId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>housinggame.player.group_id</code>.
     */
    public void setGroupId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.player.group_id</code>.
     */
    public UInteger getGroupId() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>housinggame.player.welfaretype_id</code>.
     */
    public void setWelfaretypeId(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.player.welfaretype_id</code>.
     */
    public UInteger getWelfaretypeId() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, String, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, String, UInteger, UInteger, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Player.PLAYER.ID;
    }

    @Override
    public Field<String> field2() {
        return Player.PLAYER.CODE;
    }

    @Override
    public Field<UInteger> field3() {
        return Player.PLAYER.USER_ID;
    }

    @Override
    public Field<UInteger> field4() {
        return Player.PLAYER.GROUP_ID;
    }

    @Override
    public Field<UInteger> field5() {
        return Player.PLAYER.WELFARETYPE_ID;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public UInteger component3() {
        return getUserId();
    }

    @Override
    public UInteger component4() {
        return getGroupId();
    }

    @Override
    public UInteger component5() {
        return getWelfaretypeId();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public UInteger value3() {
        return getUserId();
    }

    @Override
    public UInteger value4() {
        return getGroupId();
    }

    @Override
    public UInteger value5() {
        return getWelfaretypeId();
    }

    @Override
    public PlayerRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public PlayerRecord value3(UInteger value) {
        setUserId(value);
        return this;
    }

    @Override
    public PlayerRecord value4(UInteger value) {
        setGroupId(value);
        return this;
    }

    @Override
    public PlayerRecord value5(UInteger value) {
        setWelfaretypeId(value);
        return this;
    }

    @Override
    public PlayerRecord values(UInteger value1, String value2, UInteger value3, UInteger value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(UInteger id, String code, UInteger userId, UInteger groupId, UInteger welfaretypeId) {
        super(Player.PLAYER);

        setId(id);
        setCode(code);
        setUserId(userId);
        setGroupId(groupId);
        setWelfaretypeId(welfaretypeId);
        resetChangedOnNotNull();
    }
}
