/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Question;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionRecord extends UpdatableRecordImpl<QuestionRecord> implements Record7<Integer, Integer, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.question.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.question.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>housinggame.question.question_number</code>.
     */
    public void setQuestionNumber(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.question.question_number</code>.
     */
    public Integer getQuestionNumber() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>housinggame.question.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.question.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>housinggame.question.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.question.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>housinggame.question.minScore</code>.
     */
    public void setMinscore(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.question.minScore</code>.
     */
    public Integer getMinscore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>housinggame.question.maxScore</code>.
     */
    public void setMaxscore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.question.maxScore</code>.
     */
    public Integer getMaxscore() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>housinggame.question.scenario_id</code>.
     */
    public void setScenarioId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.question.scenario_id</code>.
     */
    public Integer getScenarioId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Question.QUESTION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Question.QUESTION.QUESTION_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return Question.QUESTION.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Question.QUESTION.NAME;
    }

    @Override
    public Field<Integer> field5() {
        return Question.QUESTION.MINSCORE;
    }

    @Override
    public Field<Integer> field6() {
        return Question.QUESTION.MAXSCORE;
    }

    @Override
    public Field<Integer> field7() {
        return Question.QUESTION.SCENARIO_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getQuestionNumber();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Integer component5() {
        return getMinscore();
    }

    @Override
    public Integer component6() {
        return getMaxscore();
    }

    @Override
    public Integer component7() {
        return getScenarioId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getQuestionNumber();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Integer value5() {
        return getMinscore();
    }

    @Override
    public Integer value6() {
        return getMaxscore();
    }

    @Override
    public Integer value7() {
        return getScenarioId();
    }

    @Override
    public QuestionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public QuestionRecord value2(Integer value) {
        setQuestionNumber(value);
        return this;
    }

    @Override
    public QuestionRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public QuestionRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public QuestionRecord value5(Integer value) {
        setMinscore(value);
        return this;
    }

    @Override
    public QuestionRecord value6(Integer value) {
        setMaxscore(value);
        return this;
    }

    @Override
    public QuestionRecord value7(Integer value) {
        setScenarioId(value);
        return this;
    }

    @Override
    public QuestionRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestionRecord
     */
    public QuestionRecord() {
        super(Question.QUESTION);
    }

    /**
     * Create a detached, initialised QuestionRecord
     */
    public QuestionRecord(Integer id, Integer questionNumber, String description, String name, Integer minscore, Integer maxscore, Integer scenarioId) {
        super(Question.QUESTION);

        setId(id);
        setQuestionNumber(questionNumber);
        setDescription(description);
        setName(name);
        setMinscore(minscore);
        setMaxscore(maxscore);
        setScenarioId(scenarioId);
        resetChangedOnNotNull();
    }
}
