/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Question;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionRecord extends UpdatableRecordImpl<QuestionRecord> implements Record5<UInteger, UInteger, String, String, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.question.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.question.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.question.question_number</code>.
     */
    public void setQuestionNumber(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.question.question_number</code>.
     */
    public UInteger getQuestionNumber() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>housinggame.question.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.question.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>housinggame.question.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.question.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>housinggame.question.scenario_id</code>.
     */
    public void setScenarioId(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.question.scenario_id</code>.
     */
    public UInteger getScenarioId() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, String, String, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, UInteger, String, String, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Question.QUESTION.ID;
    }

    @Override
    public Field<UInteger> field2() {
        return Question.QUESTION.QUESTION_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return Question.QUESTION.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Question.QUESTION.NAME;
    }

    @Override
    public Field<UInteger> field5() {
        return Question.QUESTION.SCENARIO_ID;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public UInteger component2() {
        return getQuestionNumber();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public UInteger component5() {
        return getScenarioId();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public UInteger value2() {
        return getQuestionNumber();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public UInteger value5() {
        return getScenarioId();
    }

    @Override
    public QuestionRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public QuestionRecord value2(UInteger value) {
        setQuestionNumber(value);
        return this;
    }

    @Override
    public QuestionRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public QuestionRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public QuestionRecord value5(UInteger value) {
        setScenarioId(value);
        return this;
    }

    @Override
    public QuestionRecord values(UInteger value1, UInteger value2, String value3, String value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestionRecord
     */
    public QuestionRecord() {
        super(Question.QUESTION);
    }

    /**
     * Create a detached, initialised QuestionRecord
     */
    public QuestionRecord(UInteger id, UInteger questionNumber, String description, String name, UInteger scenarioId) {
        super(Question.QUESTION);

        setId(id);
        setQuestionNumber(questionNumber);
        setDescription(description);
        setName(name);
        setScenarioId(scenarioId);
        resetChangedOnNotNull();
    }
}
