/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Welfaretype;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WelfaretypeRecord extends UpdatableRecordImpl<WelfaretypeRecord> implements Record10<UInteger, String, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.welfaretype.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.welfaretype.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.welfaretype.initial_satisfaction</code>.
     */
    public void setInitialSatisfaction(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.initial_satisfaction</code>.
     */
    public UInteger getInitialSatisfaction() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>housinggame.welfaretype.initial_money</code>.
     */
    public void setInitialMoney(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.initial_money</code>.
     */
    public UInteger getInitialMoney() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>housinggame.welfaretype.maximum_mortgage</code>.
     */
    public void setMaximumMortgage(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.maximum_mortgage</code>.
     */
    public UInteger getMaximumMortgage() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>housinggame.welfaretype.living_costs</code>.
     */
    public void setLivingCosts(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.living_costs</code>.
     */
    public UInteger getLivingCosts() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>housinggame.welfaretype.income</code>.
     */
    public void setIncome(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.income</code>.
     */
    public UInteger getIncome() {
        return (UInteger) get(6);
    }

    /**
     * Setter for
     * <code>housinggame.welfaretype.satisfaction_cost_per_point</code>.
     */
    public void setSatisfactionCostPerPoint(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>housinggame.welfaretype.satisfaction_cost_per_point</code>.
     */
    public UInteger getSatisfactionCostPerPoint() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>housinggame.welfaretype.preferred_house_rating</code>.
     */
    public void setPreferredHouseRating(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.preferred_house_rating</code>.
     */
    public UInteger getPreferredHouseRating() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>housinggame.welfaretype.scenario_id</code>.
     */
    public void setScenarioId(UInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>housinggame.welfaretype.scenario_id</code>.
     */
    public UInteger getScenarioId() {
        return (UInteger) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UInteger, String, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UInteger, String, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Welfaretype.WELFARETYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return Welfaretype.WELFARETYPE.NAME;
    }

    @Override
    public Field<UInteger> field3() {
        return Welfaretype.WELFARETYPE.INITIAL_SATISFACTION;
    }

    @Override
    public Field<UInteger> field4() {
        return Welfaretype.WELFARETYPE.INITIAL_MONEY;
    }

    @Override
    public Field<UInteger> field5() {
        return Welfaretype.WELFARETYPE.MAXIMUM_MORTGAGE;
    }

    @Override
    public Field<UInteger> field6() {
        return Welfaretype.WELFARETYPE.LIVING_COSTS;
    }

    @Override
    public Field<UInteger> field7() {
        return Welfaretype.WELFARETYPE.INCOME;
    }

    @Override
    public Field<UInteger> field8() {
        return Welfaretype.WELFARETYPE.SATISFACTION_COST_PER_POINT;
    }

    @Override
    public Field<UInteger> field9() {
        return Welfaretype.WELFARETYPE.PREFERRED_HOUSE_RATING;
    }

    @Override
    public Field<UInteger> field10() {
        return Welfaretype.WELFARETYPE.SCENARIO_ID;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UInteger component3() {
        return getInitialSatisfaction();
    }

    @Override
    public UInteger component4() {
        return getInitialMoney();
    }

    @Override
    public UInteger component5() {
        return getMaximumMortgage();
    }

    @Override
    public UInteger component6() {
        return getLivingCosts();
    }

    @Override
    public UInteger component7() {
        return getIncome();
    }

    @Override
    public UInteger component8() {
        return getSatisfactionCostPerPoint();
    }

    @Override
    public UInteger component9() {
        return getPreferredHouseRating();
    }

    @Override
    public UInteger component10() {
        return getScenarioId();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UInteger value3() {
        return getInitialSatisfaction();
    }

    @Override
    public UInteger value4() {
        return getInitialMoney();
    }

    @Override
    public UInteger value5() {
        return getMaximumMortgage();
    }

    @Override
    public UInteger value6() {
        return getLivingCosts();
    }

    @Override
    public UInteger value7() {
        return getIncome();
    }

    @Override
    public UInteger value8() {
        return getSatisfactionCostPerPoint();
    }

    @Override
    public UInteger value9() {
        return getPreferredHouseRating();
    }

    @Override
    public UInteger value10() {
        return getScenarioId();
    }

    @Override
    public WelfaretypeRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value3(UInteger value) {
        setInitialSatisfaction(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value4(UInteger value) {
        setInitialMoney(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value5(UInteger value) {
        setMaximumMortgage(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value6(UInteger value) {
        setLivingCosts(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value7(UInteger value) {
        setIncome(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value8(UInteger value) {
        setSatisfactionCostPerPoint(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value9(UInteger value) {
        setPreferredHouseRating(value);
        return this;
    }

    @Override
    public WelfaretypeRecord value10(UInteger value) {
        setScenarioId(value);
        return this;
    }

    @Override
    public WelfaretypeRecord values(UInteger value1, String value2, UInteger value3, UInteger value4, UInteger value5, UInteger value6, UInteger value7, UInteger value8, UInteger value9, UInteger value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WelfaretypeRecord
     */
    public WelfaretypeRecord() {
        super(Welfaretype.WELFARETYPE);
    }

    /**
     * Create a detached, initialised WelfaretypeRecord
     */
    public WelfaretypeRecord(UInteger id, String name, UInteger initialSatisfaction, UInteger initialMoney, UInteger maximumMortgage, UInteger livingCosts, UInteger income, UInteger satisfactionCostPerPoint, UInteger preferredHouseRating, UInteger scenarioId) {
        super(Welfaretype.WELFARETYPE);

        setId(id);
        setName(name);
        setInitialSatisfaction(initialSatisfaction);
        setInitialMoney(initialMoney);
        setMaximumMortgage(maximumMortgage);
        setLivingCosts(livingCosts);
        setIncome(income);
        setSatisfactionCostPerPoint(satisfactionCostPerPoint);
        setPreferredHouseRating(preferredHouseRating);
        setScenarioId(scenarioId);
        resetChangedOnNotNull();
    }
}
