/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.tudelft.simulation.housinggame.data.Housinggame;
import nl.tudelft.simulation.housinggame.data.Indexes;
import nl.tudelft.simulation.housinggame.data.Keys;
import nl.tudelft.simulation.housinggame.data.tables.records.BidRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bid extends TableImpl<BidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>housinggame.bid</code>
     */
    public static final Bid BID = new Bid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BidRecord> getRecordType() {
        return BidRecord.class;
    }

    /**
     * The column <code>housinggame.bid.id</code>.
     */
    public final TableField<BidRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>housinggame.bid.price</code>.
     */
    public final TableField<BidRecord, Integer> PRICE = createField(DSL.name("price"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>housinggame.bid.groupround_id</code>.
     */
    public final TableField<BidRecord, UInteger> GROUPROUND_ID = createField(DSL.name("groupround_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>housinggame.bid.house_id</code>.
     */
    public final TableField<BidRecord, UInteger> HOUSE_ID = createField(DSL.name("house_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    private Bid(Name alias, Table<BidRecord> aliased) {
        this(alias, aliased, null);
    }

    private Bid(Name alias, Table<BidRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>housinggame.bid</code> table reference
     */
    public Bid(String alias) {
        this(DSL.name(alias), BID);
    }

    /**
     * Create an aliased <code>housinggame.bid</code> table reference
     */
    public Bid(Name alias) {
        this(alias, BID);
    }

    /**
     * Create a <code>housinggame.bid</code> table reference
     */
    public Bid() {
        this(DSL.name("bid"), null);
    }

    public <O extends Record> Bid(Table<O> child, ForeignKey<O, BidRecord> key) {
        super(child, key, BID);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Housinggame.HOUSINGGAME;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BID_FK_BID_GROUPROUND1_IDX, Indexes.BID_FK_BID_HOUSE1_IDX);
    }

    @Override
    public Identity<BidRecord, UInteger> getIdentity() {
        return (Identity<BidRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<BidRecord> getPrimaryKey() {
        return Keys.KEY_BID_PRIMARY;
    }

    @Override
    public List<UniqueKey<BidRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BID_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<BidRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_BID_GROUPROUND1, Keys.FK_BID_HOUSE1);
    }

    private transient Groupround _groupround;
    private transient House _house;

    /**
     * Get the implicit join path to the <code>housinggame.groupround</code>
     * table.
     */
    public Groupround groupround() {
        if (_groupround == null)
            _groupround = new Groupround(this, Keys.FK_BID_GROUPROUND1);

        return _groupround;
    }

    /**
     * Get the implicit join path to the <code>housinggame.house</code> table.
     */
    public House house() {
        if (_house == null)
            _house = new House(this, Keys.FK_BID_HOUSE1);

        return _house;
    }

    @Override
    public Bid as(String alias) {
        return new Bid(DSL.name(alias), this);
    }

    @Override
    public Bid as(Name alias) {
        return new Bid(alias, this);
    }

    @Override
    public Bid as(Table<?> alias) {
        return new Bid(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bid rename(String name) {
        return new Bid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bid rename(Name name) {
        return new Bid(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bid rename(Table<?> name) {
        return new Bid(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, Integer, UInteger, UInteger> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super UInteger, ? super Integer, ? super UInteger, ? super UInteger, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super UInteger, ? super Integer, ? super UInteger, ? super UInteger, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
