/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.tudelft.simulation.housinggame.data.Housinggame;
import nl.tudelft.simulation.housinggame.data.Indexes;
import nl.tudelft.simulation.housinggame.data.Keys;
import nl.tudelft.simulation.housinggame.data.tables.records.GrouproundRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groupround extends TableImpl<GrouproundRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>housinggame.groupround</code>
     */
    public static final Groupround GROUPROUND = new Groupround();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrouproundRecord> getRecordType() {
        return GrouproundRecord.class;
    }

    /**
     * The column <code>housinggame.groupround.id</code>.
     */
    public final TableField<GrouproundRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>housinggame.groupround.timestamp</code>.
     */
    public final TableField<GrouproundRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>housinggame.groupround.pluvial_flood_intensity</code>.
     */
    public final TableField<GrouproundRecord, Integer> PLUVIAL_FLOOD_INTENSITY = createField(DSL.name("pluvial_flood_intensity"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>housinggame.groupround.fluvial_flood_intensity</code>.
     */
    public final TableField<GrouproundRecord, Integer> FLUVIAL_FLOOD_INTENSITY = createField(DSL.name("fluvial_flood_intensity"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>housinggame.groupround.group_state</code>.
     */
    public final TableField<GrouproundRecord, String> GROUP_STATE = createField(DSL.name("group_state"), SQLDataType.VARCHAR(24).nullable(false).defaultValue(DSL.field(DSL.raw("'LOGIN'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>housinggame.groupround.round_number</code>.
     */
    public final TableField<GrouproundRecord, Integer> ROUND_NUMBER = createField(DSL.name("round_number"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>housinggame.groupround.group_id</code>.
     */
    public final TableField<GrouproundRecord, Integer> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Groupround(Name alias, Table<GrouproundRecord> aliased) {
        this(alias, aliased, null);
    }

    private Groupround(Name alias, Table<GrouproundRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>housinggame.groupround</code> table reference
     */
    public Groupround(String alias) {
        this(DSL.name(alias), GROUPROUND);
    }

    /**
     * Create an aliased <code>housinggame.groupround</code> table reference
     */
    public Groupround(Name alias) {
        this(alias, GROUPROUND);
    }

    /**
     * Create a <code>housinggame.groupround</code> table reference
     */
    public Groupround() {
        this(DSL.name("groupround"), null);
    }

    public <O extends Record> Groupround(Table<O> child, ForeignKey<O, GrouproundRecord> key) {
        super(child, key, GROUPROUND);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Housinggame.HOUSINGGAME;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GROUPROUND_FK_GROUPROUND_GROUP1_IDX);
    }

    @Override
    public Identity<GrouproundRecord, Integer> getIdentity() {
        return (Identity<GrouproundRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GrouproundRecord> getPrimaryKey() {
        return Keys.KEY_GROUPROUND_PRIMARY;
    }

    @Override
    public List<UniqueKey<GrouproundRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_GROUPROUND_ID_UNIQUE, Keys.KEY_GROUPROUND_ROUND_UNIQUE);
    }

    @Override
    public List<ForeignKey<GrouproundRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_GROUPROUND_GROUP1);
    }

    private transient Group _group;

    /**
     * Get the implicit join path to the <code>housinggame.group</code> table.
     */
    public Group group() {
        if (_group == null)
            _group = new Group(this, Keys.FK_GROUPROUND_GROUP1);

        return _group;
    }

    @Override
    public Groupround as(String alias) {
        return new Groupround(DSL.name(alias), this);
    }

    @Override
    public Groupround as(Name alias) {
        return new Groupround(alias, this);
    }

    @Override
    public Groupround as(Table<?> alias) {
        return new Groupround(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Groupround rename(String name) {
        return new Groupround(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Groupround rename(Name name) {
        return new Groupround(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Groupround rename(Table<?> name) {
        return new Groupround(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, LocalDateTime, Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Integer, ? super LocalDateTime, ? super Integer, ? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Integer, ? super LocalDateTime, ? super Integer, ? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
