/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.tudelft.simulation.housinggame.data.Housinggame;
import nl.tudelft.simulation.housinggame.data.Indexes;
import nl.tudelft.simulation.housinggame.data.Keys;
import nl.tudelft.simulation.housinggame.data.tables.records.InitialhousemeasureRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Initialhousemeasure extends TableImpl<InitialhousemeasureRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>housinggame.initialhousemeasure</code>
     */
    public static final Initialhousemeasure INITIALHOUSEMEASURE = new Initialhousemeasure();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InitialhousemeasureRecord> getRecordType() {
        return InitialhousemeasureRecord.class;
    }

    /**
     * The column <code>housinggame.initialhousemeasure.id</code>.
     */
    public final TableField<InitialhousemeasureRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>housinggame.initialhousemeasure.name</code>.
     */
    public final TableField<InitialhousemeasureRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>housinggame.initialhousemeasure.round</code>.
     */
    public final TableField<InitialhousemeasureRecord, UInteger> ROUND = createField(DSL.name("round"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>housinggame.initialhousemeasure.measuretype_id</code>.
     */
    public final TableField<InitialhousemeasureRecord, UInteger> MEASURETYPE_ID = createField(DSL.name("measuretype_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>housinggame.initialhousemeasure.house_id</code>.
     */
    public final TableField<InitialhousemeasureRecord, UInteger> HOUSE_ID = createField(DSL.name("house_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    private Initialhousemeasure(Name alias, Table<InitialhousemeasureRecord> aliased) {
        this(alias, aliased, null);
    }

    private Initialhousemeasure(Name alias, Table<InitialhousemeasureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>housinggame.initialhousemeasure</code> table
     * reference
     */
    public Initialhousemeasure(String alias) {
        this(DSL.name(alias), INITIALHOUSEMEASURE);
    }

    /**
     * Create an aliased <code>housinggame.initialhousemeasure</code> table
     * reference
     */
    public Initialhousemeasure(Name alias) {
        this(alias, INITIALHOUSEMEASURE);
    }

    /**
     * Create a <code>housinggame.initialhousemeasure</code> table reference
     */
    public Initialhousemeasure() {
        this(DSL.name("initialhousemeasure"), null);
    }

    public <O extends Record> Initialhousemeasure(Table<O> child, ForeignKey<O, InitialhousemeasureRecord> key) {
        super(child, key, INITIALHOUSEMEASURE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Housinggame.HOUSINGGAME;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INITIALHOUSEMEASURE_FK_INITIALHOUSEMEASURE_HOUSE1_IDX, Indexes.INITIALHOUSEMEASURE_FK_INITIALHOUSEMEASURE_MEASURETYPE1_IDX);
    }

    @Override
    public Identity<InitialhousemeasureRecord, UInteger> getIdentity() {
        return (Identity<InitialhousemeasureRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<InitialhousemeasureRecord> getPrimaryKey() {
        return Keys.KEY_INITIALHOUSEMEASURE_PRIMARY;
    }

    @Override
    public List<UniqueKey<InitialhousemeasureRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_INITIALHOUSEMEASURE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<InitialhousemeasureRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_INITIALHOUSEMEASURE_MEASURETYPE1, Keys.FK_INITIALHOUSEMEASURE_HOUSE1);
    }

    private transient Measuretype _measuretype;
    private transient House _house;

    /**
     * Get the implicit join path to the <code>housinggame.measuretype</code>
     * table.
     */
    public Measuretype measuretype() {
        if (_measuretype == null)
            _measuretype = new Measuretype(this, Keys.FK_INITIALHOUSEMEASURE_MEASURETYPE1);

        return _measuretype;
    }

    /**
     * Get the implicit join path to the <code>housinggame.house</code> table.
     */
    public House house() {
        if (_house == null)
            _house = new House(this, Keys.FK_INITIALHOUSEMEASURE_HOUSE1);

        return _house;
    }

    @Override
    public Initialhousemeasure as(String alias) {
        return new Initialhousemeasure(DSL.name(alias), this);
    }

    @Override
    public Initialhousemeasure as(Name alias) {
        return new Initialhousemeasure(alias, this);
    }

    @Override
    public Initialhousemeasure as(Table<?> alias) {
        return new Initialhousemeasure(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Initialhousemeasure rename(String name) {
        return new Initialhousemeasure(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Initialhousemeasure rename(Name name) {
        return new Initialhousemeasure(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Initialhousemeasure rename(Table<?> name) {
        return new Initialhousemeasure(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, String, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super UInteger, ? super String, ? super UInteger, ? super UInteger, ? super UInteger, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super UInteger, ? super String, ? super UInteger, ? super UInteger, ? super UInteger, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
