/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.tudelft.simulation.housinggame.data.Housinggame;
import nl.tudelft.simulation.housinggame.data.Indexes;
import nl.tudelft.simulation.housinggame.data.Keys;
import nl.tudelft.simulation.housinggame.data.tables.records.ScenarioparametersRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function13;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scenarioparameters extends TableImpl<ScenarioparametersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>housinggame.scenarioparameters</code>
     */
    public static final Scenarioparameters SCENARIOPARAMETERS = new Scenarioparameters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScenarioparametersRecord> getRecordType() {
        return ScenarioparametersRecord.class;
    }

    /**
     * The column <code>housinggame.scenarioparameters.id</code>.
     */
    public final TableField<ScenarioparametersRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>housinggame.scenarioparameters.name</code>.
     */
    public final TableField<ScenarioparametersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.pluvial_repair_costs</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> PLUVIAL_REPAIR_COSTS = createField(DSL.name("pluvial_repair_costs"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.pluvial_satisfaction_penalty</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> PLUVIAL_SATISFACTION_PENALTY = createField(DSL.name("pluvial_satisfaction_penalty"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.fluvial_repair_costs</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> FLUVIAL_REPAIR_COSTS = createField(DSL.name("fluvial_repair_costs"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.fluvial_satisfaction_penalty</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> FLUVIAL_SATISFACTION_PENALTY = createField(DSL.name("fluvial_satisfaction_penalty"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.satisfaction_debt_penalty</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> SATISFACTION_DEBT_PENALTY = createField(DSL.name("satisfaction_debt_penalty"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.satisfaction_house_rating_change</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> SATISFACTION_HOUSE_RATING_CHANGE = createField(DSL.name("satisfaction_house_rating_change"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.satisfaction_move_penalty</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> SATISFACTION_MOVE_PENALTY = createField(DSL.name("satisfaction_move_penalty"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>housinggame.scenarioparameters.flood_repair_cost</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> FLOOD_REPAIR_COST = createField(DSL.name("flood_repair_cost"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.flood_satisfaction_penalty</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> FLOOD_SATISFACTION_PENALTY = createField(DSL.name("flood_satisfaction_penalty"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.mortgage_percentage</code>.
     */
    public final TableField<ScenarioparametersRecord, Double> MORTGAGE_PERCENTAGE = createField(DSL.name("mortgage_percentage"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column
     * <code>housinggame.scenarioparameters.default_language_id</code>.
     */
    public final TableField<ScenarioparametersRecord, UInteger> DEFAULT_LANGUAGE_ID = createField(DSL.name("default_language_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    private Scenarioparameters(Name alias, Table<ScenarioparametersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Scenarioparameters(Name alias, Table<ScenarioparametersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>housinggame.scenarioparameters</code> table
     * reference
     */
    public Scenarioparameters(String alias) {
        this(DSL.name(alias), SCENARIOPARAMETERS);
    }

    /**
     * Create an aliased <code>housinggame.scenarioparameters</code> table
     * reference
     */
    public Scenarioparameters(Name alias) {
        this(alias, SCENARIOPARAMETERS);
    }

    /**
     * Create a <code>housinggame.scenarioparameters</code> table reference
     */
    public Scenarioparameters() {
        this(DSL.name("scenarioparameters"), null);
    }

    public <O extends Record> Scenarioparameters(Table<O> child, ForeignKey<O, ScenarioparametersRecord> key) {
        super(child, key, SCENARIOPARAMETERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Housinggame.HOUSINGGAME;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SCENARIOPARAMETERS_FK_SCENARIOPARAMETERS_LANGUAGE1_IDX);
    }

    @Override
    public Identity<ScenarioparametersRecord, UInteger> getIdentity() {
        return (Identity<ScenarioparametersRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ScenarioparametersRecord> getPrimaryKey() {
        return Keys.KEY_SCENARIOPARAMETERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<ScenarioparametersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SCENARIOPARAMETERS_ID_UNIQUE, Keys.KEY_SCENARIOPARAMETERS_NAME_UNIQUE);
    }

    @Override
    public List<ForeignKey<ScenarioparametersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SCENARIOPARAMETERS_LANGUAGE1);
    }

    private transient Language _language;

    /**
     * Get the implicit join path to the <code>housinggame.language</code>
     * table.
     */
    public Language language() {
        if (_language == null)
            _language = new Language(this, Keys.FK_SCENARIOPARAMETERS_LANGUAGE1);

        return _language;
    }

    @Override
    public Scenarioparameters as(String alias) {
        return new Scenarioparameters(DSL.name(alias), this);
    }

    @Override
    public Scenarioparameters as(Name alias) {
        return new Scenarioparameters(alias, this);
    }

    @Override
    public Scenarioparameters as(Table<?> alias) {
        return new Scenarioparameters(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Scenarioparameters rename(String name) {
        return new Scenarioparameters(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Scenarioparameters rename(Name name) {
        return new Scenarioparameters(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Scenarioparameters rename(Table<?> name) {
        return new Scenarioparameters(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<UInteger, String, Double, Double, Double, Double, Double, Double, Double, Double, Double, Double, UInteger> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function13<? super UInteger, ? super String, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super UInteger, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function13<? super UInteger, ? super String, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super Double, ? super UInteger, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
