/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data;


import nl.tudelft.simulation.housinggame.data.tables.Community;
import nl.tudelft.simulation.housinggame.data.tables.Gamesession;
import nl.tudelft.simulation.housinggame.data.tables.Gameversion;
import nl.tudelft.simulation.housinggame.data.tables.Group;
import nl.tudelft.simulation.housinggame.data.tables.Groupround;
import nl.tudelft.simulation.housinggame.data.tables.House;
import nl.tudelft.simulation.housinggame.data.tables.Housegroup;
import nl.tudelft.simulation.housinggame.data.tables.Housetransaction;
import nl.tudelft.simulation.housinggame.data.tables.Initialhousemeasure;
import nl.tudelft.simulation.housinggame.data.tables.Label;
import nl.tudelft.simulation.housinggame.data.tables.Languagegroup;
import nl.tudelft.simulation.housinggame.data.tables.Measure;
import nl.tudelft.simulation.housinggame.data.tables.Measuretype;
import nl.tudelft.simulation.housinggame.data.tables.Movingreason;
import nl.tudelft.simulation.housinggame.data.tables.Newseffects;
import nl.tudelft.simulation.housinggame.data.tables.Newsitem;
import nl.tudelft.simulation.housinggame.data.tables.Player;
import nl.tudelft.simulation.housinggame.data.tables.Playerround;
import nl.tudelft.simulation.housinggame.data.tables.Question;
import nl.tudelft.simulation.housinggame.data.tables.Questionscore;
import nl.tudelft.simulation.housinggame.data.tables.Scenario;
import nl.tudelft.simulation.housinggame.data.tables.Scenarioparameters;
import nl.tudelft.simulation.housinggame.data.tables.Tax;
import nl.tudelft.simulation.housinggame.data.tables.Welfaretype;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in housinggame.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMUNITY_FK_COMMUNITY_GAMEVERSION1_IDX = Internal.createIndex(DSL.name("fk_community_gameversion1_idx"), Community.COMMUNITY, new OrderField[] { Community.COMMUNITY.GAMEVERSION_ID }, false);
    public static final Index GAMESESSION_FK_GAMESESSION_GAMEVERSION1_IDX = Internal.createIndex(DSL.name("fk_gamesession_gameversion1_idx"), Gamesession.GAMESESSION, new OrderField[] { Gamesession.GAMESESSION.GAMEVERSION_ID }, false);
    public static final Index GAMEVERSION_FK_GAMEVERSION_LANGUAGEGROUP1_IDX = Internal.createIndex(DSL.name("fk_gameversion_languagegroup1_idx"), Gameversion.GAMEVERSION, new OrderField[] { Gameversion.GAMEVERSION.LANGUAGEGROUP_ID }, false);
    public static final Index GROUP_FK_GROUP_GAMESESSION1_IDX = Internal.createIndex(DSL.name("fk_group_gamesession1_idx"), Group.GROUP, new OrderField[] { Group.GROUP.GAMESESSION_ID }, false);
    public static final Index GROUP_FK_GROUP_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_group_scenario1_idx"), Group.GROUP, new OrderField[] { Group.GROUP.SCENARIO_ID }, false);
    public static final Index GROUP_FK_GROUP_USER1_IDX = Internal.createIndex(DSL.name("fk_group_user1_idx"), Group.GROUP, new OrderField[] { Group.GROUP.FACILITATOR_ID }, false);
    public static final Index GROUPROUND_FK_GROUPROUND_GROUP1_IDX = Internal.createIndex(DSL.name("fk_groupround_group1_idx"), Groupround.GROUPROUND, new OrderField[] { Groupround.GROUPROUND.GROUP_ID }, false);
    public static final Index HOUSE_FK_HOUSE_COMMUNITY1_IDX = Internal.createIndex(DSL.name("fk_house_community1_idx"), House.HOUSE, new OrderField[] { House.HOUSE.COMMUNITY_ID }, false);
    public static final Index HOUSEGROUP_FK_HOUSEGROUP_GROUP1_IDX = Internal.createIndex(DSL.name("fk_housegroup_group1_idx"), Housegroup.HOUSEGROUP, new OrderField[] { Housegroup.HOUSEGROUP.GROUP_ID }, false);
    public static final Index HOUSEGROUP_FK_HOUSEROUND_HOUSE1_IDX = Internal.createIndex(DSL.name("fk_houseround_house1_idx"), Housegroup.HOUSEGROUP, new OrderField[] { Housegroup.HOUSEGROUP.HOUSE_ID }, false);
    public static final Index HOUSEGROUP_FK_HOUSEROUND_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_houseround_player1_idx"), Housegroup.HOUSEGROUP, new OrderField[] { Housegroup.HOUSEGROUP.OWNER_ID }, false);
    public static final Index HOUSETRANSACTION_FK_HOUSETRANSACTION_HOUSEGROUP1_IDX = Internal.createIndex(DSL.name("fk_housetransaction_housegroup1_idx"), Housetransaction.HOUSETRANSACTION, new OrderField[] { Housetransaction.HOUSETRANSACTION.HOUSEGROUP_ID }, false);
    public static final Index HOUSETRANSACTION_FK_HOUSETRANSACTION_PLAYERROUND1_IDX = Internal.createIndex(DSL.name("fk_housetransaction_playerround1_idx"), Housetransaction.HOUSETRANSACTION, new OrderField[] { Housetransaction.HOUSETRANSACTION.PLAYERROUND_ID }, false);
    public static final Index INITIALHOUSEMEASURE_FK_INITIALHOUSEMEASURE_HOUSE1_IDX = Internal.createIndex(DSL.name("fk_initialhousemeasure_house1_idx"), Initialhousemeasure.INITIALHOUSEMEASURE, new OrderField[] { Initialhousemeasure.INITIALHOUSEMEASURE.HOUSE_ID }, false);
    public static final Index INITIALHOUSEMEASURE_FK_INITIALHOUSEMEASURE_MEASURETYPE1_IDX = Internal.createIndex(DSL.name("fk_initialhousemeasure_measuretype1_idx"), Initialhousemeasure.INITIALHOUSEMEASURE, new OrderField[] { Initialhousemeasure.INITIALHOUSEMEASURE.MEASURETYPE_ID }, false);
    public static final Index LABEL_FK_LABEL_LANGUAGEGROUP1_IDX = Internal.createIndex(DSL.name("fk_label_languagegroup1_idx"), Label.LABEL, new OrderField[] { Label.LABEL.LANGUAGEGROUP_ID }, false);
    public static final Index LANGUAGEGROUP_FK_LANGUAGES_LANGUAGE1_IDX = Internal.createIndex(DSL.name("fk_languages_language1_idx"), Languagegroup.LANGUAGEGROUP, new OrderField[] { Languagegroup.LANGUAGEGROUP.LANGUAGE_ID1 }, false);
    public static final Index LANGUAGEGROUP_FK_LANGUAGES_LANGUAGE2_IDX = Internal.createIndex(DSL.name("fk_languages_language2_idx"), Languagegroup.LANGUAGEGROUP, new OrderField[] { Languagegroup.LANGUAGEGROUP.LANGUAGE_ID2 }, false);
    public static final Index LANGUAGEGROUP_FK_LANGUAGES_LANGUAGE3_IDX = Internal.createIndex(DSL.name("fk_languages_language3_idx"), Languagegroup.LANGUAGEGROUP, new OrderField[] { Languagegroup.LANGUAGEGROUP.LANGUAGE_ID3 }, false);
    public static final Index LANGUAGEGROUP_FK_LANGUAGES_LANGUAGE4_IDX = Internal.createIndex(DSL.name("fk_languages_language4_idx"), Languagegroup.LANGUAGEGROUP, new OrderField[] { Languagegroup.LANGUAGEGROUP.LANGUAGE_ID4 }, false);
    public static final Index MEASURE_FK_MEASURE_HOUSEROUND1_IDX = Internal.createIndex(DSL.name("fk_measure_houseround1_idx"), Measure.MEASURE, new OrderField[] { Measure.MEASURE.HOUSEGROUP_ID }, false);
    public static final Index MEASURE_FK_MEASURE_MEASURETYPE1_IDX = Internal.createIndex(DSL.name("fk_measure_measuretype1_idx"), Measure.MEASURE, new OrderField[] { Measure.MEASURE.MEASURETYPE_ID }, false);
    public static final Index MEASURETYPE_FK_MEASURETYPE_GAMEVERSION1_IDX = Internal.createIndex(DSL.name("fk_measuretype_gameversion1_idx"), Measuretype.MEASURETYPE, new OrderField[] { Measuretype.MEASURETYPE.GAMEVERSION_ID }, false);
    public static final Index MOVINGREASON_FK_MOVINGREASON_GAMEVERSION1_IDX = Internal.createIndex(DSL.name("fk_movingreason_gameversion1_idx"), Movingreason.MOVINGREASON, new OrderField[] { Movingreason.MOVINGREASON.GAMEVERSION_ID }, false);
    public static final Index NEWSEFFECTS_FK_NEWSEFFECTS_COMMUNITY1_IDX = Internal.createIndex(DSL.name("fk_newseffects_community1_idx"), Newseffects.NEWSEFFECTS, new OrderField[] { Newseffects.NEWSEFFECTS.COMMUNITY_ID }, false);
    public static final Index NEWSEFFECTS_FK_NEWSEFFECTS_NEWSITEM1_IDX = Internal.createIndex(DSL.name("fk_newseffects_newsitem1_idx"), Newseffects.NEWSEFFECTS, new OrderField[] { Newseffects.NEWSEFFECTS.NEWSITEM_ID }, false);
    public static final Index NEWSITEM_FK_NEWSITEM_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_newsitem_scenario1_idx"), Newsitem.NEWSITEM, new OrderField[] { Newsitem.NEWSITEM.SCENARIO_ID }, false);
    public static final Index PLAYER_FK_PLAYER_GROUP1_IDX = Internal.createIndex(DSL.name("fk_player_group1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.GROUP_ID }, false);
    public static final Index PLAYER_FK_PLAYER_USER1_IDX = Internal.createIndex(DSL.name("fk_player_user1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.USER_ID }, false);
    public static final Index PLAYER_FK_PLAYER_WELFARETYPE1_IDX = Internal.createIndex(DSL.name("fk_player_welfaretype1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.WELFARETYPE_ID }, false);
    public static final Index PLAYERROUND_FK_PLAYERROUND_GROUPROUND1_IDX = Internal.createIndex(DSL.name("fk_playerround_groupround1_idx"), Playerround.PLAYERROUND, new OrderField[] { Playerround.PLAYERROUND.GROUPROUND_ID }, false);
    public static final Index PLAYERROUND_FK_PLAYERROUND_HOUSEGROUP1_IDX = Internal.createIndex(DSL.name("fk_playerround_housegroup1_idx"), Playerround.PLAYERROUND, new OrderField[] { Playerround.PLAYERROUND.START_HOUSEGROUP_ID }, false);
    public static final Index PLAYERROUND_FK_PLAYERROUND_HOUSEGROUP2_IDX = Internal.createIndex(DSL.name("fk_playerround_housegroup2_idx"), Playerround.PLAYERROUND, new OrderField[] { Playerround.PLAYERROUND.FINAL_HOUSEGROUP_ID }, false);
    public static final Index PLAYERROUND_FK_PLAYERROUND_HOUSETRANSACTION1_IDX = Internal.createIndex(DSL.name("fk_playerround_housetransaction1_idx"), Playerround.PLAYERROUND, new OrderField[] { Playerround.PLAYERROUND.ACTIVE_TRANSACTION_ID }, false);
    public static final Index PLAYERROUND_FK_PLAYERROUND_MOVINGREASON1_IDX = Internal.createIndex(DSL.name("fk_playerround_movingreason1_idx"), Playerround.PLAYERROUND, new OrderField[] { Playerround.PLAYERROUND.MOVINGREASON_ID }, false);
    public static final Index PLAYERROUND_FK_PLAYERROUND_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_playerround_player1_idx"), Playerround.PLAYERROUND, new OrderField[] { Playerround.PLAYERROUND.PLAYER_ID }, false);
    public static final Index QUESTION_FK_QUESTION_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_question_scenario1_idx"), Question.QUESTION, new OrderField[] { Question.QUESTION.SCENARIO_ID }, false);
    public static final Index QUESTIONSCORE_FK_QUESTIONSCORE_PLAYERROUND1_IDX = Internal.createIndex(DSL.name("fk_questionscore_playerround1_idx"), Questionscore.QUESTIONSCORE, new OrderField[] { Questionscore.QUESTIONSCORE.PLAYERROUND_ID }, false);
    public static final Index QUESTIONSCORE_FK_QUESTIONSCORE_QUESTION1_IDX = Internal.createIndex(DSL.name("fk_questionscore_question1_idx"), Questionscore.QUESTIONSCORE, new OrderField[] { Questionscore.QUESTIONSCORE.QUESTION_ID }, false);
    public static final Index SCENARIO_FK_SCENARIO_GAMEVERSION1_IDX = Internal.createIndex(DSL.name("fk_scenario_gameversion1_idx"), Scenario.SCENARIO, new OrderField[] { Scenario.SCENARIO.GAMEVERSION_ID }, false);
    public static final Index SCENARIO_FK_SCENARIO_SCENARIOPARAMETERS1_IDX = Internal.createIndex(DSL.name("fk_scenario_scenarioparameters1_idx"), Scenario.SCENARIO, new OrderField[] { Scenario.SCENARIO.SCENARIOPARAMETERS_ID }, false);
    public static final Index SCENARIOPARAMETERS_FK_SCENARIOPARAMETERS_LANGUAGE1_IDX = Internal.createIndex(DSL.name("fk_scenarioparameters_language1_idx"), Scenarioparameters.SCENARIOPARAMETERS, new OrderField[] { Scenarioparameters.SCENARIOPARAMETERS.DEFAULT_LANGUAGE_ID }, false);
    public static final Index TAX_FK_TAX_COMMUNITY1_IDX = Internal.createIndex(DSL.name("fk_tax_community1_idx"), Tax.TAX, new OrderField[] { Tax.TAX.COMMUNITY_ID }, false);
    public static final Index WELFARETYPE_FK_WELFARETYPE_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_welfaretype_scenario1_idx"), Welfaretype.WELFARETYPE, new OrderField[] { Welfaretype.WELFARETYPE.SCENARIO_ID }, false);
}
